package com.example.mienspa.model;
// Generated May 19, 2023, 4:12:14 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ordersprodetail generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "ordersprodetail", catalog = "mienspa")
public class OrdersProDetail implements java.io.Serializable {

	private Integer ordProId;
	private OrdersPro orderspro;
	private String ordProProductName;
	private int ordProProductPrice;
	private int ordProQuantity;

	public OrdersProDetail() {
	}

	public OrdersProDetail(OrdersPro orderspro, String ordProProductName, int ordProProductPrice, int ordProQuantity) {
		this.orderspro = orderspro;
		this.ordProProductName = ordProProductName;
		this.ordProProductPrice = ordProProductPrice;
		this.ordProQuantity = ordProQuantity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ordPro_Id", unique = true, nullable = false)
	public Integer getOrdProId() {
		return this.ordProId;
	}

	public void setOrdProId(Integer ordProId) {
		this.ordProId = ordProId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ordPro_OrderId", nullable = false)
	public OrdersPro getOrderspro() {
		return this.orderspro;
	}

	public void setOrderspro(OrdersPro orderspro) {
		this.orderspro = orderspro;
	}

	@Column(name = "ordPro_ProductName", nullable = false)
	public String getOrdProProductName() {
		return this.ordProProductName;
	}

	public void setOrdProProductName(String ordProProductName) {
		this.ordProProductName = ordProProductName;
	}

	@Column(name = "ordPro_ProductPrice", nullable = false)
	public int getOrdProProductPrice() {
		return this.ordProProductPrice;
	}

	public void setOrdProProductPrice(int ordProProductPrice) {
		this.ordProProductPrice = ordProProductPrice;
	}

	@Column(name = "ordPro_Quantity", nullable = false)
	public int getOrdProQuantity() {
		return this.ordProQuantity;
	}

	public void setOrdProQuantity(int ordProQuantity) {
		this.ordProQuantity = ordProQuantity;
	}

}
