package com.example.mienspa.model;
// Generated May 19, 2023, 4:12:14 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Serce generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "serce", catalog = "mienspa")
public class Serce implements java.io.Serializable {

	private String seId;
	private String seName;
	private float sePrice;
	private String seDescription;
	private String seNote;
	private String seImage;
	private Boolean seTurnOn;
	private Date createdAt;
	private Date updatedAt;
	private Boolean isDelete;

	public Serce() {
	}

	public Serce(String seId, String seName, float sePrice, String seDescription) {
		this.seId = seId;
		this.seName = seName;
		this.sePrice = sePrice;
		this.seDescription = seDescription;
	}

	public Serce(String seId, String seName, int sePrice, String seDescription, String seNote, String seImage,
			Boolean seTurnOn, Date createdAt, Date updatedAt, Boolean isDelete) {
		this.seId = seId;
		this.seName = seName;
		this.sePrice = sePrice;
		this.seDescription = seDescription;
		this.seNote = seNote;
		this.seImage = seImage;
		this.seTurnOn = seTurnOn;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.isDelete = isDelete;
	}

	@Id

	@Column(name = "se_Id", unique = true, nullable = false, length = 128)
	public String getSeId() {
		return this.seId;
	}

	public void setSeId(String seId) {
		this.seId = seId;
	}

	@Column(name = "se_Name", nullable = false, length = 65535)
	public String getSeName() {
		return this.seName;
	}

	public void setSeName(String seName) {
		this.seName = seName;
	}

	@Column(name = "se_Price", nullable = false)
	public float getSePrice() {
		return this.sePrice;
	}

	public void setSePrice(float sePrice) {
		this.sePrice = sePrice;
	}

	@Column(name = "se_Description", nullable = false, length = 65535)
	public String getSeDescription() {
		return this.seDescription;
	}

	public void setSeDescription(String seDescription) {
		this.seDescription = seDescription;
	}

	@Column(name = "se_Note", length = 65535)
	public String getSeNote() {
		return this.seNote;
	}

	public void setSeNote(String seNote) {
		this.seNote = seNote;
	}

	@Column(name = "se_Image", length = 250)
	public String getSeImage() {
		return this.seImage;
	}

	public void setSeImage(String seImage) {
		this.seImage = seImage;
	}

	@Column(name = "se_TurnOn")
	public Boolean getSeTurnOn() {
		return this.seTurnOn;
	}

	public void setSeTurnOn(Boolean seTurnOn) {
		this.seTurnOn = seTurnOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 26)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 26)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "isDelete")
	public Boolean getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(Boolean isDelete) {
		this.isDelete = isDelete;
	}

}
